name: CD
on:
  push:
    tags: ["v*"]
  release:
    types: [published]
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy
    uses: andrewscwei/workflows/.github/workflows/npm-deploy.yml@master
    with:
      create-release: true
      run-command: npm run build
    secrets:
      npm-auth-token: ${{ secrets.NPM_AUTH }}
  notify:
    name: Notify
    needs: [deploy]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/telegram-action@v1.0.0
        with:
          success: ${{ needs.deploy.result == 'success' }}
          bot-token: ${{ secrets.TELEGRAM_DEVOPS_BOT_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_DEVOPS_CHAT_ID }}
